### ISSUE TITLE
Auto Updater not working

### ISSUE THREAD

**Issue by valnoxy** [valnoxy/GoAwayEdge#16]
Cannot check for updates. Might be an issue with getting the current version when compiled as release build.

**Comment by valnoxy** [comment]
yup

```
[*] Please go away Edge!
[*] Hooked into process via IFEO successfully.
[*] Command line args:

--update

System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at GoAwayEdge.Common.Updater.CheckForAppUpdate() in C:\Users\jonas\source\repos\GoAwayEdge_v1\GoAwayEdge\Common\Updater.cs:line 154
```
